name: Actualizar Efemérides Diarias Bien FM

on:
  schedule:
    - cron: '5 3 * * *' # Corre a la madrugada solo
  workflow_dispatch: # Permite correrlo a mano

# Permisos necesarios para publicar en GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Ejecutar script de efemérides
      run: python generar_rss.py

    - name: Configurar Pages
      uses: actions/configure-pages@v4

    - name: Subir artefacto de Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # Sube toda la carpeta raíz, incluyendo el index.html generado

    - name: Publicar en GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
