name: Actualizar Efemérides Diarias Bien FM

on:
  schedule:
    # Corre todos los días a las 00:05 AM hora de Argentina (03:05 AM UTC)
    - cron: '5 3 * * *'
  workflow_dispatch: # Permite correrlo a mano

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Ejecutar script de efemérides
      run: python generar_rss.py

    - name: Confirmar cambios y subir al repositorio
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add efemerides_bienfm.xml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automatización: Efemérides del día actualizadas" && git push)
